// ⚠️  נוצר על ידי extraction/build_cbt_index.py — אל תערוך ידנית.
//
//  **אינדקס בלבד.** המקטעים עצמם יושבים ב-KV תחת `cbt:<id>`,
//  כי 2.7MB טקסט אינם שייכים לבנדל של Worker. מה שכאן קטן דיו
//  כדי להיטען תמיד, ולכן הבחירה — שצריכה לראות את כל האפשרויות —
//  רצה בלי אף קריאת רשת.
export const LIBRARY = [
 {
  "id": "beck-basics/00-introduction-to-cognitive-behavior-therapy",
  "book": "beck-basics",
  "title": "Introduction To Cognitive Behavior Therapy",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 5520,
  "terms": [
   "therapy",
   "cognitive",
   "behavior",
   "beck",
   "treatment",
   "thoughts",
   "client",
   "yourself",
   "techniques",
   "session",
   "first",
   "therapist",
   "skills",
   "many"
  ],
  "bcts": [
   "coping-plan",
   "relapse-prevention",
   "prompt-commitment",
   "check-nrt"
  ]
 },
 {
  "id": "beck-basics/01-overview-of-treatment",
  "book": "beck-basics",
  "title": "Overview Of Treatment",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 3478,
  "terms": [
   "treatment",
   "therapy",
   "session",
   "client",
   "sessions",
   "action",
   "principle",
   "goals",
   "help",
   "cognitive",
   "positive",
   "plans",
   "therapeutic",
   "conceptualization"
  ],
  "bcts": [
   "coping-plan",
   "summary-and-homework",
   "relapse-prevention"
  ]
 },
 {
  "id": "beck-basics/02-cognitive-conceptualization",
  "book": "beck-basics",
  "title": "Cognitive Conceptualization",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2178,
  "terms": [
   "beliefs",
   "conceptualization",
   "thoughts",
   "cognitive",
   "people",
   "reader",
   "automatic",
   "situation",
   "understand",
   "behavior",
   "treatment",
   "client",
   "core",
   "positive"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/03-helpless-core-beliefs",
  "book": "beck-basics",
  "title": "Helpless Core Beliefs",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 7384,
  "terms": [
   "beliefs",
   "core",
   "belief",
   "automatic",
   "behavior",
   "cognitive",
   "thoughts",
   "thought",
   "data",
   "conceptualization",
   "situation",
   "help",
   "negative",
   "client"
  ],
  "bcts": [
   "identify-triggers",
   "coping-plan",
   "prompt-commitment"
  ]
 },
 {
  "id": "beck-basics/04-practice-exercise",
  "book": "beck-basics",
  "title": "Practice        Exercise",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 2440,
  "terms": [
   "client",
   "session",
   "treatment",
   "relationship",
   "therapeutic",
   "therapy",
   "help",
   "feel",
   "need",
   "you'll",
   "feedback",
   "positive",
   "first",
   "skills"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/05-using-self-disclosure",
  "book": "beck-basics",
  "title": "Using Self-Disclosure",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 3087,
  "terms": [
   "judith",
   "client",
   "maria",
   "care",
   "relationship",
   "therapy",
   "think",
   "negative",
   "feel",
   "session",
   "well",
   "know",
   "want",
   "help"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/06-the-evaluation-session",
  "book": "beck-basics",
  "title": "The Evaluation Session",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 764,
  "terms": [
   "session",
   "evaluation",
   "treatment",
   "client",
   "plan",
   "information",
   "part",
   "whether",
   "initial",
   "assessment",
   "collect",
   "diagnosis",
   "cognitive",
   "disorder"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/07-part-1-starting-the-evaluation-session",
  "book": "beck-basics",
  "title": "Part 1: Starting The Evaluation Session",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2134,
  "terms": [
   "judith",
   "treatment",
   "session",
   "time",
   "need",
   "good",
   "client",
   "know",
   "usually",
   "tell",
   "whether",
   "okay",
   "like",
   "anything"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/08-saldana",
  "book": "beck-basics",
  "title": "Saldana",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1788,
  "terms": [
   "judith",
   "plan",
   "treatment",
   "we'll",
   "week",
   "every",
   "therapy",
   "action",
   "goals",
   "good",
   "give",
   "depressed",
   "okay",
   "yourself"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/09-part-6-summarizing-and-eliciting-feedback",
  "book": "beck-basics",
  "title": "Part 6: Summarizing And Eliciting Feedback",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 541,
  "terms": [
   "session",
   "client",
   "treatment",
   "plan",
   "evaluation",
   "you'll",
   "therapy",
   "first",
   "week",
   "judith",
   "told",
   "health",
   "start",
   "next"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/10-the-first-therapy-session",
  "book": "beck-basics",
  "title": "The First Therapy Session",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 554,
  "terms": [
   "session",
   "plan",
   "action",
   "first",
   "client",
   "treatment",
   "psychoeducation",
   "check",
   "provide",
   "therapy",
   "aspirations",
   "goals",
   "you'll",
   "cognitive"
  ],
  "bcts": [
   "coping-plan",
   "check-nrt"
  ]
 },
 {
  "id": "beck-basics/11-mood-check",
  "book": "beck-basics",
  "title": "Mood Check",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 8701,
  "terms": [
   "judith",
   "good",
   "think",
   "session",
   "therapy",
   "like",
   "want",
   "depressed",
   "week",
   "goals",
   "thought",
   "thoughts",
   "important",
   "just"
  ],
  "bcts": [
   "coping-plan",
   "check-nrt"
  ]
 },
 {
  "id": "beck-basics/12-activity-scheduling",
  "book": "beck-basics",
  "title": "Activity Scheduling",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 765,
  "terms": [
   "activity",
   "activities",
   "thoughts",
   "sense",
   "pleasure",
   "mood",
   "doing",
   "behavior",
   "inactivity",
   "common",
   "feel",
   "scheduling",
   "depressed",
   "least"
  ],
  "bcts": [
   "change-routine"
  ]
 },
 {
  "id": "beck-basics/13-scheduling-activities",
  "book": "beck-basics",
  "title": "Scheduling Activities",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 2908,
  "terms": [
   "judith",
   "activities",
   "maria",
   "better",
   "activity",
   "feel",
   "good",
   "things",
   "think",
   "important",
   "chart",
   "make",
   "scheduling",
   "week"
  ],
  "bcts": [
   "change-routine",
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/14-types-of-activities",
  "book": "beck-basics",
  "title": "Types Of Activities",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1303,
  "terms": [
   "activities",
   "maria",
   "judith",
   "activity",
   "scheduling",
   "pleasure",
   "thoughts",
   "garden",
   "chart",
   "mastery",
   "connection",
   "time",
   "mind",
   "doing"
  ],
  "bcts": [
   "change-routine",
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/15-action-plans",
  "book": "beck-basics",
  "title": "Action Plans",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 447,
  "terms": [
   "action",
   "plans",
   "client",
   "session",
   "behavior",
   "cognitive",
   "every",
   "through",
   "better",
   "thinking",
   "learn",
   "practice",
   "plan",
   "therapy"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/16-types-of-action-plan-items",
  "book": "beck-basics",
  "title": "Types Of Action Plan Items",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 7708,
  "terms": [
   "action",
   "plan",
   "plans",
   "maria",
   "judith",
   "doing",
   "session",
   "therapy",
   "help",
   "think",
   "client",
   "time",
   "thoughts",
   "week"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/17-treatment-planning",
  "book": "beck-basics",
  "title": "Treatment Planning",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 222,
  "terms": [
   "plan",
   "treatment",
   "accomplish",
   "therapy",
   "client",
   "destination",
   "main",
   "highways",
   "you'll",
   "create",
   "sessions",
   "goal",
   "planning",
   "helpful"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/18-accomplishing-therapeutic-objectives",
  "book": "beck-basics",
  "title": "Accomplishing Therapeutic Objectives",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 347,
  "terms": [
   "treatment",
   "therapeutic",
   "objectives",
   "experiences",
   "values",
   "increase",
   "positive",
   "techniques",
   "planning",
   "sound",
   "aspirations",
   "sense",
   "purpose",
   "develop"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/19-planning-treatment-across-sessions",
  "book": "beck-basics",
  "title": "Planning Treatment Across Sessions",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 608,
  "terms": [
   "treatment",
   "therapy",
   "plan",
   "steps",
   "identify",
   "obstacles",
   "taking",
   "goals",
   "each",
   "goal",
   "positive",
   "cognitive",
   "planning",
   "phase"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/20-overall-treatment-plan",
  "book": "beck-basics",
  "title": "Overall Treatment Plan",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 573,
  "terms": [
   "obstacles",
   "plan",
   "potential",
   "thoughts",
   "look",
   "automatic",
   "online",
   "therapy",
   "increase",
   "positive",
   "self",
   "ex-wife",
   "evaluate",
   "treatment"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/21-planning-individual-sessions",
  "book": "beck-basics",
  "title": "Planning Individual Sessions",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2857,
  "terms": [
   "client",
   "goal",
   "session",
   "agenda",
   "judith",
   "maria",
   "therapy",
   "yourself",
   "plan",
   "issue",
   "problem",
   "item",
   "time",
   "need"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/22-structuring-sessions",
  "book": "beck-basics",
  "title": "Structuring Sessions",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 5846,
  "terms": [
   "judith",
   "session",
   "week",
   "agenda",
   "action",
   "plan",
   "therapy",
   "think",
   "important",
   "you'll",
   "sessions",
   "mood",
   "good",
   "client"
  ],
  "bcts": [
   "coping-plan",
   "check-nrt",
   "change-routine"
  ]
 },
 {
  "id": "beck-basics/23-problems-in",
  "book": "beck-basics",
  "title": "Problems In",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 5874,
  "terms": [
   "session",
   "maria",
   "client",
   "agenda",
   "problem",
   "judith",
   "problems",
   "week",
   "sessions",
   "therapy",
   "time",
   "structure",
   "help",
   "just"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/24-identifying-automatic-thoughts",
  "book": "beck-basics",
  "title": "Identifying Automatic Thoughts",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 188,
  "terms": [
   "thoughts",
   "automatic",
   "identifying",
   "cognitive",
   "model",
   "situation",
   "often",
   "situations",
   "negative",
   "review",
   "suggests",
   "interpretation",
   "rather",
   "itself"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/25-characteristics-of-automatic-thoughts",
  "book": "beck-basics",
  "title": "Characteristics Of Automatic Thoughts",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1144,
  "terms": [
   "thoughts",
   "automatic",
   "thought",
   "behavior",
   "aware",
   "unhelpful",
   "example",
   "always",
   "situation",
   "client",
   "thinking",
   "feels",
   "going",
   "physiological"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "beck-basics/26-explaining-automatic-thoughts-to-clients",
  "book": "beck-basics",
  "title": "Explaining Automatic Thoughts To Clients",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1964,
  "terms": [
   "thoughts",
   "automatic",
   "thought",
   "judith",
   "maria",
   "emotion",
   "through",
   "thinking",
   "mind",
   "going",
   "behavior",
   "really",
   "able",
   "cognitive"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/27-difficulties-in-eliciting-automatic-thoughts",
  "book": "beck-basics",
  "title": "Difficulties In Eliciting Automatic Thoughts",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 1463,
  "terms": [
   "thoughts",
   "judith",
   "automatic",
   "through",
   "mind",
   "going",
   "situation",
   "client",
   "identifying",
   "play",
   "you're",
   "thinking",
   "just",
   "help"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/28-emotions",
  "book": "beck-basics",
  "title": "Emotions",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2810,
  "terms": [
   "emotion",
   "emotions",
   "judith",
   "feel",
   "thoughts",
   "positive",
   "maria",
   "negative",
   "think",
   "important",
   "felt",
   "like",
   "automatic",
   "help"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/29-increasing-negative-emotion",
  "book": "beck-basics",
  "title": "Increasing Negative Emotion",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 637,
  "terms": [
   "negative",
   "emotion",
   "emotions",
   "techniques",
   "maria",
   "help",
   "beliefs",
   "cognitive",
   "thoughts",
   "dysfunctional",
   "upset",
   "behavior",
   "cognitions",
   "experiencing"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/30-evaluating-automatic-thoughts",
  "book": "beck-basics",
  "title": "Evaluating Automatic Thoughts",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 806,
  "terms": [
   "thought",
   "thoughts",
   "automatic",
   "important",
   "evaluate",
   "client",
   "therapy",
   "address",
   "you'll",
   "work",
   "focus",
   "time",
   "emotion",
   "treatment"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/31-oo-sss-seuss",
  "book": "beck-basics",
  "title": "Oo     Sss Seuss",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1042,
  "terms": [
   "thought",
   "automatic",
   "questions",
   "thoughts",
   "socratic",
   "true",
   "happen",
   "think",
   "thinking",
   "judith",
   "feel",
   "client",
   "questioning",
   "method"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/32-clinical-tips",
  "book": "beck-basics",
  "title": "Clinical     Tips",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 4997,
  "terms": [
   "automatic",
   "thought",
   "judith",
   "thoughts",
   "want",
   "questions",
   "think",
   "help",
   "client",
   "situation",
   "thinking",
   "example",
   "evidence",
   "good"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/33-responding-10-automatic-thoughts",
  "book": "beck-basics",
  "title": "Responding 10 Automatic Thoughts",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 205,
  "terms": [
   "thoughts",
   "automatic",
   "between",
   "sessions",
   "worksheet",
   "figures",
   "previous",
   "help",
   "important",
   "session",
   "responses",
   "questions",
   "therapy",
   "teach"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/34-composing-therapy-notes",
  "book": "beck-basics",
  "title": "Composing Therapy Notes",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 2591,
  "terms": [
   "notes",
   "therapy",
   "thoughts",
   "example",
   "thinking",
   "think",
   "read",
   "worksheet",
   "just",
   "cognitive",
   "automatic",
   "thought",
   "remember",
   "true"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/35-clinical-tips",
  "book": "beck-basics",
  "title": "Clinical Tips",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 1299,
  "terms": [
   "worksheet",
   "thought",
   "automatic",
   "thoughts",
   "questions",
   "judith",
   "think",
   "better",
   "maria",
   "client",
   "next",
   "help",
   "okay",
   "therapy"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/36-integrating-mindfulness-into-cbt",
  "book": "beck-basics",
  "title": "Integrating Mindfulness Into Cbt",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 1606,
  "terms": [
   "mindfulness",
   "thoughts",
   "experience",
   "practice",
   "formal",
   "rumination",
   "informal",
   "thought",
   "process",
   "exercise",
   "breath",
   "focus",
   "internal",
   "negative"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/37-introducing-mindfulness-to-clients",
  "book": "beck-basics",
  "title": "Introducing Mindfulness To Clients",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 714,
  "terms": [
   "mindfulness",
   "pauses",
   "seconds",
   "back",
   "notice",
   "focus",
   "breath",
   "judith",
   "rumination",
   "thoughts",
   "mind",
   "like",
   "going",
   "eyes"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/38-the-aware-technique",
  "book": "beck-basics",
  "title": "The Aware Technique",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 451,
  "terms": [
   "mindfulness",
   "practice",
   "technique",
   "steps",
   "yourself",
   "worry",
   "experience",
   "attention",
   "open",
   "internal",
   "therapy",
   "aware",
   "anxiety",
   "rumination"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/39-introduction-to-beliefs",
  "book": "beck-basics",
  "title": "Introduction To Beliefs",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2658,
  "terms": [
   "beliefs",
   "core",
   "schemas",
   "negative",
   "belief",
   "judith",
   "adaptive",
   "depressed",
   "mode",
   "positive",
   "others",
   "world",
   "good",
   "people"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/40-identifying-maladaptive-core-beliefs",
  "book": "beck-basics",
  "title": "Identifying Maladaptive Core Beliefs",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "dialogue",
  "words": 1640,
  "terms": [
   "beliefs",
   "belief",
   "core",
   "automatic",
   "thoughts",
   "client",
   "negative",
   "intermediate",
   "behavior",
   "thought",
   "help",
   "people",
   "rule",
   "attitude"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/41-deciding-when-to-modify-a-dysfunctional-belief",
  "book": "beck-basics",
  "title": "Deciding When To Modify A Dysfunctional Belief",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2374,
  "terms": [
   "belief",
   "core",
   "beliefs",
   "judith",
   "like",
   "incompetent",
   "client",
   "think",
   "automatic",
   "time",
   "idea",
   "dysfunctional",
   "yourself",
   "competent"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/42-modifying-beliefs",
  "book": "beck-basics",
  "title": "Modifying Beliefs",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1652,
  "terms": [
   "beliefs",
   "positive",
   "adaptive",
   "competent",
   "belief",
   "evidence",
   "chart",
   "think",
   "person",
   "experiences",
   "like",
   "competence",
   "important",
   "data"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/43-modifying-maladaptive-beliefs",
  "book": "beck-basics",
  "title": "Modifying Maladaptive Beliefs",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 4630,
  "terms": [
   "judith",
   "beliefs",
   "help",
   "belief",
   "incompetent",
   "because",
   "well",
   "therapy",
   "intellectual",
   "failure",
   "think",
   "change",
   "people",
   "techniques"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/44-additional-techniques",
  "book": "beck-basics",
  "title": "Additional Techniques",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 911,
  "terms": [
   "techniques",
   "therapy",
   "behavior",
   "negative",
   "relaxation",
   "exercises",
   "emotion",
   "help",
   "cognitive",
   "problem",
   "valued",
   "experience",
   "additional",
   "many"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/45-skills-training",
  "book": "beck-basics",
  "title": "Skills Training",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 4467,
  "terms": [
   "judith",
   "maria",
   "problem",
   "want",
   "step",
   "much",
   "like",
   "think",
   "help",
   "you'll",
   "make",
   "good",
   "exposure",
   "skills"
  ],
  "bcts": [
   "identify-triggers",
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/46-clinical-tips",
  "book": "beck-basics",
  "title": "Clinical Tips",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 279,
  "terms": [
   "techniques",
   "make",
   "yourself",
   "help",
   "need",
   "working",
   "mood",
   "summary",
   "many",
   "affect",
   "client",
   "option",
   "versus",
   "time"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/47-imagery",
  "book": "beck-basics",
  "title": "Imagery",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 208,
  "terms": [
   "images",
   "imagery",
   "positive",
   "automatic",
   "visual",
   "husband",
   "negative",
   "identify",
   "distressing",
   "spontaneous",
   "mery",
   "experience",
   "thoughts",
   "unspoken"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/48-inducing-positive-images",
  "book": "beck-basics",
  "title": "Inducing Positive Images",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 3601,
  "terms": [
   "judith",
   "images",
   "image",
   "imagine",
   "okay",
   "techniques",
   "really",
   "help",
   "yourself",
   "like",
   "doing",
   "feeling",
   "imagery",
   "positive"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/49-termination-and",
  "book": "beck-basics",
  "title": "Termination And",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 2692,
  "terms": [
   "sessions",
   "therapy",
   "judith",
   "better",
   "maria",
   "relapse",
   "skills",
   "week",
   "help",
   "termination",
   "you'll",
   "treatment",
   "problems",
   "depressed"
  ],
  "bcts": [
   "relapse-prevention",
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/50-preparing-for-setbacks-after-termination",
  "book": "beck-basics",
  "title": "Preparing For Setbacks After Termination",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 947,
  "terms": [
   "sessions",
   "termination",
   "therapy",
   "treatment",
   "make",
   "after",
   "relapse",
   "important",
   "booster",
   "thoughts",
   "future",
   "help",
   "signs",
   "setback"
  ],
  "bcts": [
   "relapse-prevention"
  ]
 },
 {
  "id": "beck-basics/51-problems-in-therapy",
  "book": "beck-basics",
  "title": "Problems In Therapy",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 231,
  "terms": [
   "problems",
   "client",
   "difficulties",
   "therapy",
   "arise",
   "every",
   "remediate",
   "kind",
   "therapists",
   "conceptualizing",
   "help",
   "reasonable",
   "skills",
   "stuck"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/52-uncovering-the-existence-of-a-problem",
  "book": "beck-basics",
  "title": "Uncovering The Existence Of A Problem",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 2282,
  "terms": [
   "client",
   "therapy",
   "session",
   "problem",
   "goals",
   "problems",
   "treatment",
   "thoughts",
   "action",
   "automatic",
   "cognitive",
   "sessions",
   "help",
   "cognitions"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/53-stuck-points",
  "book": "beck-basics",
  "title": "Stuck Points",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 1128,
  "terms": [
   "client",
   "beck",
   "therapy",
   "problem",
   "treatment",
   "session",
   "cognitive",
   "behavior",
   "problems",
   "doing",
   "institute",
   "sessions",
   "conceptualization",
   "plan"
  ],
  "bcts": [
   "coping-plan",
   "check-nrt"
  ]
 },
 {
  "id": "beck-basics/54-appendix-b",
  "book": "beck-basics",
  "title": "Appendix B",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 1839,
  "terms": [
   "symptoms",
   "high",
   "years",
   "became",
   "work",
   "began",
   "depression",
   "good",
   "himself",
   "treatment",
   "family",
   "history",
   "friends",
   "school"
  ],
  "bcts": [
   "check-nrt",
   "coping-plan"
  ]
 },
 {
  "id": "beck-basics/55-part-five-treatment-plan",
  "book": "beck-basics",
  "title": "Part Five: Treatment Plan",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 909,
  "terms": [
   "treatment",
   "sense",
   "thoughts",
   "depression",
   "social",
   "positive",
   "evaluated",
   "activities",
   "automatic",
   "behavioral",
   "rumination",
   "able",
   "sessions",
   "plan"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/56-appendix-c",
  "book": "beck-basics",
  "title": "Appendix C",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "theory",
  "words": 314,
  "terms": [
   "anxiety",
   "anxious",
   "watch",
   "avoid",
   "steps",
   "accept",
   "normal",
   "experience",
   "become",
   "intense",
   "just",
   "doesn",
   "danger",
   "dangerous"
  ],
  "bcts": []
 },
 {
  "id": "beck-basics/57-appendix-d",
  "book": "beck-basics",
  "title": "Appendix D",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 11034,
  "terms": [
   "therapy",
   "cognitive",
   "beliefs",
   "thoughts",
   "session",
   "beck",
   "automatic",
   "york",
   "identifying",
   "treatment",
   "problems",
   "clinical",
   "conceptualization",
   "dysfunctional"
  ],
  "bcts": [
   "coping-plan",
   "change-routine",
   "check-nrt",
   "relapse-prevention",
   "summary-and-homework",
   "identify-triggers"
  ]
 },
 {
  "id": "beck-basics/58-psychology-cognitive-behavior-therapy",
  "book": "beck-basics",
  "title": "Psychology Cognitive Behavior Therapy",
  "src": "Cognitive Behavior Therapy: Basics and Beyond — Judith S. Beck",
  "kind": "exercise",
  "words": 397,
  "terms": [
   "psychology",
   "therapy",
   "third",
   "edition",
   "practice",
   "cognitive",
   "text",
   "strengths",
   "professor",
   "university",
   "california",
   "behavior",
   "includes",
   "clinical"
  ],
  "bcts": []
 },
 {
  "id": "green-lynn-smoking/00-2-why-hypnosis-rationale-and-supporting-evidence",
  "book": "green-lynn-smoking",
  "title": "2. Why Hypnosis? Rationale and Supporting Evidence",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 5496,
  "terms": [
   "hypnosis",
   "smoking",
   "treatment",
   "cessation",
   "success",
   "studies",
   "rates",
   "participants",
   "reported",
   "behavioral",
   "counseling",
   "self",
   "lynn",
   "abstinence"
  ],
  "bcts": [
   "check-nrt",
   "discuss-cravings",
   "discuss-withdrawal",
   "smoking-contacts",
   "relapse-prevention",
   "assess-dependence"
  ]
 },
 {
  "id": "green-lynn-smoking/01-3-before-you-start-tips-for-facilitators",
  "book": "green-lynn-smoking",
  "title": "3. Before You Start: Tips for Facilitators",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "theory",
  "words": 6520,
  "terms": [
   "smoking",
   "participants",
   "smoke",
   "stop",
   "change",
   "program",
   "facilitators",
   "motivation",
   "goal",
   "urge",
   "reduction",
   "cessation",
   "self",
   "life"
  ],
  "bcts": [
   "discuss-cravings",
   "assess-readiness",
   "smoking-contacts",
   "identify-triggers",
   "not-a-puff",
   "prompt-commitment"
  ]
 },
 {
  "id": "green-lynn-smoking/02-4-beginning-the-program-the-first-treatment-session",
  "book": "green-lynn-smoking",
  "title": "4. Beginning the Program: The First Treatment Session",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 15352,
  "terms": [
   "smoking",
   "program",
   "participants",
   "stop",
   "hypnosis",
   "smoke",
   "first",
   "people",
   "goal",
   "time",
   "session",
   "winning",
   "edge",
   "urge"
  ],
  "bcts": [
   "discuss-cravings",
   "check-nrt",
   "identify-triggers",
   "relapse-prevention",
   "prompt-commitment",
   "smoking-contacts"
  ]
 },
 {
  "id": "green-lynn-smoking/03-5-interview-with-a-coping-model-and-self-hypnosis-script-1",
  "book": "green-lynn-smoking",
  "title": "5. Interview with a Coping Model and Self‐Hypnosis Script 1",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 3402,
  "terms": [
   "hypnosis",
   "self",
   "experience",
   "think",
   "yourself",
   "just",
   "smoking",
   "like",
   "smoke",
   "nonsmoker",
   "become",
   "program",
   "myself",
   "urge"
  ],
  "bcts": [
   "discuss-cravings",
   "prompt-commitment",
   "check-nrt"
  ]
 },
 {
  "id": "green-lynn-smoking/04-6-handouts-and-worksheets-to-accompany-session-1",
  "book": "green-lynn-smoking",
  "title": "6. Handouts and Worksheets to Accompany Session 1",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 4005,
  "terms": [
   "smoking",
   "session",
   "stop",
   "smoke",
   "people",
   "number",
   "hypnosis",
   "date",
   "handouts",
   "worksheets",
   "feel",
   "accompany",
   "program",
   "times"
  ],
  "bcts": [
   "discuss-cravings",
   "prompt-commitment",
   "objective-verification",
   "review-progress",
   "identify-triggers",
   "smoking-contacts"
  ]
 },
 {
  "id": "green-lynn-smoking/05-7-completing-the-program-the-second-treatment-session",
  "book": "green-lynn-smoking",
  "title": "7. Completing the Program: The Second Treatment Session",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 6525,
  "terms": [
   "smoking",
   "self",
   "yourself",
   "hypnosis",
   "smoke",
   "nonsmoker",
   "urge",
   "life",
   "session",
   "participants",
   "just",
   "like",
   "second",
   "each"
  ],
  "bcts": [
   "discuss-cravings",
   "check-nrt",
   "identify-triggers",
   "prompt-commitment",
   "review-progress",
   "objective-verification"
  ]
 },
 {
  "id": "green-lynn-smoking/06-8-treatment-session-2-handouts-and-follow-up-forms",
  "book": "green-lynn-smoking",
  "title": "8. Treatment Session 2 Handouts and Follow‐Up Forms",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "theory",
  "words": 1585,
  "terms": [
   "number",
   "times",
   "listened",
   "week",
   "participants",
   "cigarettes",
   "today",
   "smoked",
   "smoking",
   "date",
   "session",
   "treatment",
   "program",
   "nonsmoker"
  ],
  "bcts": []
 },
 {
  "id": "green-lynn-smoking/07-9-common-questions-individualizing-treatment",
  "book": "green-lynn-smoking",
  "title": "9. Common Questions, Individualizing Treatment,",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 11317,
  "terms": [
   "smoking",
   "weight",
   "nicotine",
   "cessation",
   "gain",
   "cigarettes",
   "treatment",
   "women",
   "participants",
   "health",
   "likely",
   "associated",
   "among",
   "program"
  ],
  "bcts": [
   "check-nrt",
   "discuss-withdrawal",
   "discuss-cravings",
   "identify-triggers",
   "relapse-prevention",
   "assess-dependence"
  ]
 },
 {
  "id": "green-lynn-smoking/08-10-review-of-overall-program-scheme-and-forms-to-aid",
  "book": "green-lynn-smoking",
  "title": "10. Review of Overall Program Scheme and Forms to Aid",
  "src": "CBT, Mindfulness and Hypnosis for Smoking Cessation — Green & Lynn",
  "kind": "exercise",
  "words": 26850,
  "terms": [
   "smoking",
   "hypnosis",
   "cessation",
   "program",
   "journal",
   "nicotine",
   "health",
   "clinical",
   "tobacco",
   "treatment",
   "study",
   "research",
   "stop",
   "review"
  ],
  "bcts": [
   "check-nrt",
   "discuss-cravings",
   "assess-readiness",
   "assess-dependence",
   "relapse-prevention",
   "discuss-withdrawal"
  ]
 },
 {
  "id": "manning-worksheets/00-thought-feeling-physiology-and-behaviour-diaries",
  "book": "manning-worksheets",
  "title": "Thought, feeling, physiology and behaviour diaries",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 442,
  "terms": [
   "list",
   "problem",
   "feeling",
   "client",
   "diaries",
   "specific",
   "emotions",
   "progress",
   "body",
   "physiological",
   "reactions",
   "changes",
   "labelling",
   "therapy"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/01-therapy-preparation-sheet",
  "book": "manning-worksheets",
  "title": "Therapy preparation sheet",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 389,
  "terms": [
   "mood",
   "diaries",
   "therapy",
   "help",
   "activity",
   "client",
   "problem",
   "professional",
   "increase",
   "lead",
   "fluctuations",
   "schedule",
   "preparation",
   "sheet"
  ],
  "bcts": [
   "change-routine",
   "objective-verification"
  ]
 },
 {
  "id": "manning-worksheets/02-problem-list",
  "book": "manning-worksheets",
  "title": "Problem list",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 348,
  "terms": [
   "problem",
   "therapy",
   "help",
   "list",
   "useful",
   "difficulties",
   "focus",
   "problems",
   "feelings",
   "behaviours",
   "complete",
   "time",
   "make",
   "feeling"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/03-thought-feeling-physiology-and-behaviour-diaries",
  "book": "manning-worksheets",
  "title": "Thought, feeling, physiology and behaviour diaries",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 195,
  "terms": [
   "thought",
   "diaries",
   "feeling",
   "physiology",
   "behaviour",
   "once",
   "completion",
   "useful",
   "automatically",
   "thinking",
   "react",
   "makes",
   "behave",
   "awareness"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/04-intrusive-thoughts-diary",
  "book": "manning-worksheets",
  "title": "Intrusive thoughts diary",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 166,
  "terms": [
   "thoughts",
   "intrusive",
   "people",
   "often",
   "diary",
   "struggle",
   "something",
   "name",
   "suggests",
   "mind",
   "without",
   "invitation",
   "come",
   "intense"
  ],
  "bcts": [
   "objective-verification"
  ]
 },
 {
  "id": "manning-worksheets/05-mood-diaries-and-activity-schedules",
  "book": "manning-worksheets",
  "title": "Mood diaries and activity schedules",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 158,
  "terms": [
   "mood",
   "keeping",
   "diaries",
   "activity",
   "track",
   "aware",
   "result",
   "impact",
   "fluctuations",
   "aspects",
   "life",
   "schedules",
   "useful",
   "becoming"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/06-anger-diaries",
  "book": "manning-worksheets",
  "title": "Anger diaries",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 1615,
  "terms": [
   "beliefs",
   "rules",
   "longitudinal",
   "anger",
   "formulations",
   "behaviours",
   "feel",
   "rule",
   "thoughts",
   "formulation",
   "limiting",
   "people",
   "nats",
   "often"
  ],
  "bcts": [
   "objective-verification",
   "identify-triggers",
   "coping-plan"
  ]
 },
 {
  "id": "manning-worksheets/07-the-generic-cbt-model",
  "book": "manning-worksheets",
  "title": "The generic CBT model",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 227,
  "terms": [
   "cycle",
   "generic",
   "thought",
   "thoughts",
   "body",
   "likely",
   "model",
   "diary",
   "negative",
   "work",
   "mind",
   "scan",
   "bringing",
   "self-fulfilling"
  ],
  "bcts": [
   "objective-verification"
  ]
 },
 {
  "id": "manning-worksheets/08-thoughts-feelings-and-behaviour-cycle",
  "book": "manning-worksheets",
  "title": "Thoughts, feelings and behaviour cycle",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 126,
  "terms": [
   "thoughts",
   "feelings",
   "behaviour",
   "cycle",
   "increase",
   "impact",
   "problems",
   "perhaps",
   "best",
   "starting",
   "point",
   "find",
   "models",
   "work"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/09-a-model-of-social-anxiety",
  "book": "manning-worksheets",
  "title": "A model of social anxiety",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 120,
  "terms": [
   "social",
   "anxiety",
   "beliefs",
   "behaviours",
   "experience",
   "situation",
   "assumptions",
   "safety",
   "model",
   "models",
   "suggest",
   "starts",
   "initial",
   "triggering"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/10-health-anxiety-models",
  "book": "manning-worksheets",
  "title": "Health Anxiety Models",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 190,
  "terms": [
   "anxiety",
   "flower",
   "illness",
   "feel",
   "health",
   "vicious",
   "yourself",
   "behaviours",
   "model",
   "safety",
   "signs",
   "symptoms",
   "models",
   "probably"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/11-ocd-models-of-anxiety",
  "book": "manning-worksheets",
  "title": "OCD models of anxiety",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 302,
  "terms": [
   "thoughts",
   "intrusive",
   "rachman",
   "something",
   "model",
   "thought",
   "certain",
   "anxiety",
   "awareness",
   "people",
   "often",
   "evidence",
   "happened",
   "happen"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "manning-worksheets/12-a-model-for-panic",
  "book": "manning-worksheets",
  "title": "A model for panic",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "exercise",
  "words": 1421,
  "terms": [
   "thought",
   "exercise",
   "challenging",
   "exercises",
   "evidence",
   "client",
   "panic",
   "body",
   "beliefs",
   "belief",
   "symptoms",
   "reactions",
   "thinking",
   "balanced"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/13-self-refection-sheets",
  "book": "manning-worksheets",
  "title": "Self-refection sheets",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 192,
  "terms": [
   "behaviour",
   "client",
   "behaviours",
   "self-reflection",
   "encourages",
   "many",
   "problematic",
   "consequences",
   "positive",
   "distressing",
   "feelings",
   "initially",
   "systematic",
   "desensitisation"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/14-the-downward-arrow-exercise",
  "book": "manning-worksheets",
  "title": "The downward arrow exercise",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "exercise",
  "words": 210,
  "terms": [
   "exercise",
   "downward",
   "arrow",
   "yourself",
   "thoughts",
   "thought",
   "others",
   "emotional",
   "accessing",
   "painful",
   "negative",
   "awareness",
   "belief",
   "difficult"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/15-nat-challenging-form",
  "book": "manning-worksheets",
  "title": "NAT challenging form",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 140,
  "terms": [
   "thought",
   "evidence",
   "down",
   "thoughts",
   "after",
   "write",
   "against",
   "balanced",
   "challenging",
   "useful",
   "intense",
   "completed",
   "through",
   "much"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/16-belief-and-rule-challenging-exercises",
  "book": "manning-worksheets",
  "title": "Belief and rule challenging exercises",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "exercise",
  "words": 257,
  "terms": [
   "beliefs",
   "rules",
   "feel",
   "belief",
   "rule",
   "exercises",
   "part",
   "challenging",
   "huge",
   "amounts",
   "time",
   "lives",
   "self-imposed",
   "against"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/17-the-future-most-developed-self-fmds-exercise",
  "book": "manning-worksheets",
  "title": "The future most developed self (FMDS) exercise",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "exercise",
  "words": 333,
  "terms": [
   "fmds",
   "problem",
   "self",
   "exercise",
   "person",
   "think",
   "mind",
   "inside",
   "future",
   "become",
   "feel",
   "need",
   "make",
   "life"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/18-behavioural-experiments",
  "book": "manning-worksheets",
  "title": "Behavioural experiments",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 223,
  "terms": [
   "behaviour",
   "behavioural",
   "knowledge",
   "experiments",
   "change",
   "carry",
   "make",
   "prediction",
   "experiential",
   "experiment",
   "happen",
   "carried",
   "think",
   "feel"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/19-responsibility-pies",
  "book": "manning-worksheets",
  "title": "Responsibility pies",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 144,
  "terms": [
   "responsibility",
   "pies",
   "people",
   "involved",
   "aspect",
   "life",
   "yourself",
   "list",
   "useful",
   "begin",
   "take",
   "much",
   "events",
   "lives"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/20-safe-place",
  "book": "manning-worksheets",
  "title": "Safe place",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 248,
  "terms": [
   "place",
   "safe",
   "change",
   "behaviour",
   "outdoor",
   "memories",
   "conscious",
   "awareness",
   "events",
   "yourself",
   "visualisations",
   "because",
   "bring",
   "involving"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/21-positive-cbt-cycles",
  "book": "manning-worksheets",
  "title": "Positive CBT cycles",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 200,
  "terms": [
   "thought",
   "positive",
   "place",
   "balanced",
   "behaviour",
   "behaviours",
   "cycles",
   "generic",
   "information",
   "cycle",
   "mind",
   "body",
   "safety",
   "although"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/22-systematic-desensitisation-sheets",
  "book": "manning-worksheets",
  "title": "Systematic desensitisation sheets",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 214,
  "terms": [
   "desensitisation",
   "anxiety",
   "systematic",
   "item",
   "list",
   "each",
   "behaviours",
   "until",
   "sheets",
   "exposure",
   "process",
   "complete",
   "need",
   "down"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/23-exposure-sheet",
  "book": "manning-worksheets",
  "title": "Exposure sheet",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 261,
  "terms": [
   "useful",
   "handouts",
   "thinking",
   "exposure",
   "situation",
   "behaviour",
   "help",
   "yourself",
   "model",
   "feelings",
   "sheet",
   "particular",
   "anxiety",
   "after"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/24-rumination-and-worry-handout",
  "book": "manning-worksheets",
  "title": "Rumination and worry handout",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 464,
  "terms": [
   "part",
   "brain",
   "cognitive",
   "distortions",
   "animal",
   "safety",
   "feel",
   "rumination",
   "much",
   "behaviours",
   "problems",
   "view",
   "clever",
   "like"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/25-sally-professor-nut-do-you-have-anything-to",
  "book": "manning-worksheets",
  "title": "SALLY: Professor Nut. Do you have anything to",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 580,
  "terms": [
   "brain",
   "part",
   "subcortical",
   "regions",
   "system",
   "cortex",
   "prefrontal",
   "neocortex",
   "limbic",
   "anxiety",
   "people",
   "think",
   "emotional",
   "reactions"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "manning-worksheets/26-emotions-exercise",
  "book": "manning-worksheets",
  "title": "Emotions exercise",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 651,
  "terms": [
   "feelings",
   "emotions",
   "feeling",
   "mind",
   "threat",
   "focus",
   "feel",
   "emotion",
   "hand",
   "body",
   "anxiety",
   "strongly",
   "keep",
   "important"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/27-rumination-and-worry-explanation-using-dialogue",
  "book": "manning-worksheets",
  "title": "Rumination and worry – explanation using dialogue",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "dialogue",
  "words": 2795,
  "terms": [
   "thoughts",
   "mind",
   "therapist",
   "client",
   "information",
   "gregory",
   "whiteboard",
   "thought",
   "intrusive",
   "questions",
   "like",
   "think",
   "people",
   "process"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/28-examples-of-safety-behaviour-in-social-anxiety",
  "book": "manning-worksheets",
  "title": "Examples of safety behaviour in social anxiety",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 291,
  "terms": [
   "social",
   "avoid",
   "before",
   "others",
   "going",
   "ready",
   "hands",
   "anxiety",
   "diazepam",
   "carry",
   "drink",
   "situations",
   "bottle",
   "onto"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/29-examples-of-safety-behaviour-in-panic-attacks",
  "book": "manning-worksheets",
  "title": "Examples of safety behaviour in panic attacks",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 280,
  "terms": [
   "before",
   "carry",
   "fear",
   "panic",
   "situations",
   "going",
   "avoid",
   "related",
   "self",
   "body",
   "complete",
   "medical",
   "examples",
   "safety"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/30-examples-of-safety-behaviour-in-ocd",
  "book": "manning-worksheets",
  "title": "Examples of safety behaviour in OCD",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 1192,
  "terms": [
   "avoid",
   "others",
   "focus",
   "behaviour",
   "before",
   "going",
   "social",
   "people",
   "self",
   "onto",
   "anxiety",
   "leave",
   "hands",
   "assess"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/31-potential-behavioural-experiments-for-ocd",
  "book": "manning-worksheets",
  "title": "Potential behavioural experiments for OCD",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 440,
  "terms": [
   "avoid",
   "certain",
   "behaviour",
   "things",
   "check",
   "complete",
   "gradually",
   "others",
   "people",
   "activities",
   "example",
   "away",
   "reassurance",
   "intrusive"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/32-references-and-additional-reading",
  "book": "manning-worksheets",
  "title": "References and additional reading",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 596,
  "terms": [
   "social",
   "cognitive",
   "anxiety",
   "stress",
   "research",
   "overcoming",
   "robinson",
   "panic",
   "guide",
   "journal",
   "disorder",
   "therapy",
   "clark",
   "treatment"
  ],
  "bcts": []
 },
 {
  "id": "manning-worksheets/33-glossary",
  "book": "manning-worksheets",
  "title": "Glossary",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 722,
  "terms": [
   "response",
   "process",
   "thoughts",
   "brain",
   "past",
   "emotional",
   "connected",
   "mind",
   "automatic",
   "area",
   "responsible",
   "body",
   "strategies",
   "used"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "manning-worksheets/34-common-medications",
  "book": "manning-worksheets",
  "title": "Common Medications",
  "src": "CBT Worksheets — Manning & Ridgeway",
  "kind": "theory",
  "words": 195,
  "terms": [
   "anxiety",
   "prescribed",
   "inhibitor",
   "generalised",
   "reuptake",
   "benzodiazepine",
   "panic",
   "phobias",
   "selective",
   "serotonin",
   "antidepressant",
   "tricyclic",
   "social",
   "anticonvulsant"
  ],
  "bcts": []
 },
 {
  "id": "ncsct-stp/00-session-1-pre-quit-assessment",
  "book": "ncsct-stp",
  "title": "Session 1: Pre-quit Assessment",
  "src": "NCSCT Standard Treatment Programme",
  "kind": "theory",
  "words": 5566,
  "terms": [
   "smoking",
   "quit",
   "client",
   "stop",
   "date",
   "smoke",
   "medication",
   "nicotine",
   "session",
   "attempt",
   "after",
   "assessment",
   "cigarettes",
   "pre-quit"
  ],
  "bcts": [
   "check-nrt",
   "prompt-commitment",
   "discuss-cravings",
   "discuss-withdrawal",
   "assess-dependence",
   "not-a-puff",
   "past-attempts"
  ]
 },
 {
  "id": "ncsct-stp/01-session-2-quit-date",
  "book": "ncsct-stp",
  "title": "Session 2: Quit Date",
  "src": "NCSCT Standard Treatment Programme",
  "kind": "theory",
  "words": 3310,
  "terms": [
   "client",
   "quit",
   "smoking",
   "smoke",
   "date",
   "cigarettes",
   "going",
   "medication",
   "session",
   "attempt",
   "week",
   "after",
   "support",
   "using"
  ],
  "bcts": [
   "discuss-cravings",
   "check-nrt",
   "prompt-commitment",
   "discuss-withdrawal",
   "high-risk-ahead",
   "not-a-puff"
  ]
 },
 {
  "id": "ncsct-stp/02-sessions-3-4-and-5-1-2-and-3-weeks-post-quit-date",
  "book": "ncsct-stp",
  "title": "Sessions 3, 4 and 5: 1, 2 and 3 weeks post Quit Date",
  "src": "NCSCT Standard Treatment Programme",
  "kind": "theory",
  "words": 2036,
  "terms": [
   "client",
   "smoking",
   "quit",
   "week",
   "date",
   "situations",
   "puff",
   "withdrawal",
   "reading",
   "weeks",
   "post",
   "medication",
   "symptoms",
   "smoke"
  ],
  "bcts": [
   "discuss-cravings",
   "prompt-commitment",
   "high-risk-ahead",
   "discuss-withdrawal",
   "not-a-puff",
   "check-nrt"
  ]
 },
 {
  "id": "ncsct-stp/03-session-6-4-weeks-post-quit-date",
  "book": "ncsct-stp",
  "title": "Session 6: 4 weeks post Quit Date",
  "src": "NCSCT Standard Treatment Programme",
  "kind": "theory",
  "words": 3095,
  "terms": [
   "smoking",
   "client",
   "quit",
   "weeks",
   "smoke",
   "provide",
   "advise",
   "facilitate",
   "session",
   "stop",
   "information",
   "medication",
   "date",
   "general"
  ],
  "bcts": [
   "prompt-commitment",
   "discuss-cravings",
   "check-nrt",
   "not-a-puff",
   "discuss-withdrawal",
   "assess-dependence"
  ]
 },
 {
  "id": "padesky-mind-over-mood/00-mind-over-mood",
  "book": "padesky-mind-over-mood",
  "title": "Mind Over Mood",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 9292,
  "terms": [
   "thoughts",
   "mood",
   "thought",
   "life",
   "moods",
   "help",
   "marissa",
   "changes",
   "mind",
   "physical",
   "feel",
   "problems",
   "think",
   "linda"
  ],
  "bcts": [
   "check-nrt",
   "discuss-cravings"
  ]
 },
 {
  "id": "padesky-mind-over-mood/01-thought-behavior-connection",
  "book": "padesky-mind-over-mood",
  "title": "Thought-Behavior Connection",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "theory",
  "words": 419,
  "terms": [
   "thoughts",
   "positive",
   "thinking",
   "reactions",
   "sarah",
   "physical",
   "changes",
   "mood",
   "anxious",
   "solution",
   "lead",
   "information",
   "linda",
   "anxiety"
  ],
  "bcts": []
 },
 {
  "id": "padesky-mind-over-mood/02-is-changing-the-way-you-think-the-only-way",
  "book": "padesky-mind-over-mood",
  "title": "Is Changing The Way You Think The Only Way",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 11250,
  "terms": [
   "moods",
   "thoughts",
   "mood",
   "thought",
   "situation",
   "mind",
   "worksheet",
   "feel",
   "help",
   "automatic",
   "questions",
   "record",
   "images",
   "situations"
  ],
  "bcts": []
 },
 {
  "id": "padesky-mind-over-mood/03-hot-thoughts",
  "book": "padesky-mind-over-mood",
  "title": "Hot Thoughts",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 2225,
  "terms": [
   "thoughts",
   "thought",
   "mood",
   "automatic",
   "feel",
   "general",
   "each",
   "nervous",
   "anxiety",
   "questions",
   "worksheet",
   "images",
   "mind",
   "happen"
  ],
  "bcts": []
 },
 {
  "id": "padesky-mind-over-mood/04-mood-check-up",
  "book": "padesky-mind-over-mood",
  "title": "Mood Check-Up",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 17519,
  "terms": [
   "thought",
   "evidence",
   "thoughts",
   "mood",
   "alternative",
   "record",
   "balanced",
   "column",
   "marissa",
   "help",
   "support",
   "moods",
   "judy",
   "feel"
  ],
  "bcts": [
   "coping-plan"
  ]
 },
 {
  "id": "padesky-mind-over-mood/05-acceptance",
  "book": "padesky-mind-over-mood",
  "title": "Acceptance",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 5860,
  "terms": [
   "heart",
   "thoughts",
   "linda",
   "underlying",
   "experiments",
   "acceptance",
   "assumptions",
   "anxiety",
   "time",
   "assumption",
   "mood",
   "father",
   "attack",
   "mind"
  ],
  "bcts": [
   "coping-plan",
   "smoking-contacts"
  ]
 },
 {
  "id": "padesky-mind-over-mood/06-identifying-underlying-assumptions",
  "book": "padesky-mind-over-mood",
  "title": "Identifying Underlying Assumptions",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 12673,
  "terms": [
   "core",
   "beliefs",
   "belief",
   "people",
   "assumptions",
   "worksheet",
   "experiments",
   "underlying",
   "mood",
   "negative",
   "even",
   "experiences",
   "mean",
   "world"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "padesky-mind-over-mood/07-gratitude",
  "book": "padesky-mind-over-mood",
  "title": "Gratitude",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 2091,
  "terms": [
   "gratitude",
   "things",
   "worksheet",
   "grateful",
   "positive",
   "people",
   "mood",
   "journal",
   "core",
   "life",
   "others",
   "beliefs",
   "worksheets",
   "appreciate"
  ],
  "bcts": []
 },
 {
  "id": "padesky-mind-over-mood/08-acts-of-kindness",
  "book": "padesky-mind-over-mood",
  "title": "Acts Of Kindness",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 13539,
  "terms": [
   "mood",
   "depression",
   "anxiety",
   "activities",
   "mind",
   "feel",
   "help",
   "better",
   "people",
   "time",
   "worksheet",
   "things",
   "activity",
   "negative"
  ],
  "bcts": [
   "change-routine",
   "check-nrt"
  ]
 },
 {
  "id": "padesky-mind-over-mood/09-anxious-thoughts",
  "book": "padesky-mind-over-mood",
  "title": "Anxious Thoughts",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 3163,
  "terms": [
   "anxiety",
   "thoughts",
   "anxious",
   "danger",
   "images",
   "cope",
   "fear",
   "situation",
   "situations",
   "ability",
   "feel",
   "often",
   "people",
   "physical"
  ],
  "bcts": [
   "identify-triggers"
  ]
 },
 {
  "id": "padesky-mind-over-mood/10-fear-ladder",
  "book": "padesky-mind-over-mood",
  "title": "Fear Ladder",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 14315,
  "terms": [
   "anxiety",
   "anger",
   "mood",
   "people",
   "feel",
   "help",
   "mind",
   "fear",
   "angry",
   "ladder",
   "thoughts",
   "shame",
   "worksheet",
   "person"
  ],
  "bcts": [
   "check-nrt",
   "smoking-contacts",
   "coping-plan"
  ]
 },
 {
  "id": "padesky-mind-over-mood/11-responsibility-pie",
  "book": "padesky-mind-over-mood",
  "title": "Responsibility Pie",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 2040,
  "terms": [
   "shame",
   "responsibility",
   "guilt",
   "people",
   "worksheet",
   "person",
   "petra",
   "make",
   "amends",
   "time",
   "done",
   "help",
   "feel",
   "others"
  ],
  "bcts": []
 },
 {
  "id": "padesky-mind-over-mood/12-when-you-complete-this-chapter",
  "book": "padesky-mind-over-mood",
  "title": "When You Complete This Chapter",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 15591,
  "terms": [
   "mood",
   "thoughts",
   "worksheet",
   "mind",
   "thought",
   "moods",
   "skills",
   "core",
   "anxiety",
   "depression",
   "plan",
   "life",
   "poow",
   "example"
  ],
  "bcts": [
   "relapse-prevention",
   "change-routine",
   "coping-plan",
   "high-risk-ahead",
   "discuss-cravings"
  ]
 },
 {
  "id": "padesky-mind-over-mood/13-self-help",
  "book": "padesky-mind-over-mood",
  "title": "Self-Help",
  "src": "Mind Over Mood — Greenberger & Padesky",
  "kind": "exercise",
  "words": 532,
  "terms": [
   "therapy",
   "cognitive",
   "beck",
   "anxiety",
   "edition",
   "second",
   "padesky",
   "depression",
   "california",
   "change",
   "life",
   "dennis",
   "christine",
   "psychotherapy"
  ],
  "bcts": []
 }
];
